### ISSUE TITLE
Issue?

### ISSUE THREAD

**Issue by Tachyonica** [eth2353/eth2.tax#3] opened 2022-03-12 14:00 UTC
Getting: "An error occurred, please try again. If the issue persists, check the browser console for more information." Any idea what have gone wrong?

**Comment by eth2353** [comment] 2022-03-12 15:06
I got an alert about some failed requests on the website in the last 24 hours. I took some time today to figure out what went wrong. The issue was caused by the pending validators and their associated activation_epoch while they are pending.

The bug is fixed now!

**Closed by eth2353** 2022-03-12 15:06 UTC
